## Using Tensorflow like Numpy

### Tensors and Operations

In [24]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
my_tensor = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
my_tensor.shape

TensorShape([2, 3])

In [6]:
my_tensor.dtype

tf.float32

In [11]:
my_tensor[:,-2:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [14]:
my_tensor[:,1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [15]:
my_tensor + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [16]:
my_tensor / 2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]], dtype=float32)>

In [30]:
tf.sqrt(my_tensor)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

In [19]:
my_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [20]:
tf.transpose(my_tensor)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [21]:
my_tensor @ tf.transpose(my_tensor) # equivalent to tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [23]:
## can also use keras backend for these operations
K = keras.backend
K.sqrt(my_tensor)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

### Tensors and numpy

In [25]:
a = np.array([11., 22., 33.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([11., 22., 33.])>

In [26]:
my_tensor.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [27]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 121.,  484., 1089.])>

In [28]:
np.square(my_tensor)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

> Numpy uses 64bit precision by default

> tf uses 32bit by default (better for rapidity and DNN training)

### Type conversions

> you can operate between integers and floats , or even float32 and float64
> tf do not do conversion automaticly and throws exeptions 

In [31]:
tf.constant(10) + tf.constant(2.)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [32]:
tf.constant(12.) + tf.constant(10., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

### Variables

In [55]:
v = tf.Variable([[1., 2., 3.],[4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [56]:
v.assign(v*2)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [59]:
v[1,2].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 42.]], dtype=float32)>

In [51]:
v = v*2 # this change the v tensor from Variable to Tensor(constant)
v

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

> other types of  tensor objects:
>1. tf.SparseTensor     
2. tf.TensorArray 
3.tf.RaggedTensor
4.tf.string
5.tf.sets
6.tf.queues


## Customizing Models and Training Algorithms

#### Custom Loss Functions

#### Custom Activation Functions, Initializers, Regularizers, and Constraints

#### Custom Metrics

#### Custom Layers

#### Custom Models

### Computing Gradients Using Autodiff

In [62]:
def f(w1,w2):
    return 3 * w1 ** 2 + 2 * w1 * w2

In [66]:
w1, w2 = 5, 3
eps = 1e-6
print('gradient w1: ', (f(w1+eps,w2)-f(w1,w2))/eps)
print('gradient w2: ', (f(w1,w2+eps)-f(w1,w2))/eps)

gradient w1:  36.000003007075065
gradient w2:  10.000000003174137


In [67]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1,w2)
gradients = tape.gradient(z, [w1,w2])
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

> tape records all the operation done on variable inside the with 

In [68]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1,w2)
gradients1 = tape.gradient(z, [w1,w2])
gradients2 = tape.gradient(z, [w1,w2]) # throws error because tape is delited after the first use

RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

> use persistant to presiste the tape, but you should delete it once you are done with it, to release memory

In [70]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape(persistent=True) as tape:
    z = f(w1,w2)
gradients1 = tape.gradient(z, [w1,w2])
gradients2 = tape.gradient(z, [w1,w2])
del tape

> computing gradiant of constatn will get you a none

In [71]:
w1, w2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape(persistent=True) as tape:
    z = f(w1,w2)
gradients = tape.gradient(z, [w1,w2])
gradients

[None, None]